<?php defined('BASEPATH') OR exit('No direct script access allowed');
$lang['entities_categorylv2_Id'] = 'Id';
$lang['entities_categorylv2_ReferenceCategoryLv1'] = 'ReferenceCategoryLv1';
$lang['entities_categorylv2_ReferenceId'] = 'ReferenceId';
$lang['entities_categorylv2_ShortDescription'] = 'ShortDescription';
$lang['entities_categorylv2_LongDescription'] = 'LongDescription';
$lang['entities_categorylv2_AddBy'] = 'AddBy';
$lang['entities_categorylv2_AddDate'] = 'AddDate';
$lang['entities_categorylv2_EditBy'] = 'EditBy';
$lang['entities_categorylv2_EditDate'] = 'EditDate';
$lang['entities_categorylv2_Timestamp'] = 'Timestamp';
