<?php defined('BASEPATH') OR exit('No direct script access allowed');
$lang['entities_hr_data_leave_request_RequestId'] = 'RequestId';
$lang['entities_hr_data_leave_request_EmployeeId'] = 'EmployeeId';
$lang['entities_hr_data_leave_request_LeaveId'] = 'LeaveId';
$lang['entities_hr_data_leave_request_RequestDays'] = 'RequestDays';
$lang['entities_hr_data_leave_request_Status'] = 'Status';
$lang['entities_hr_data_leave_request_AddBy'] = 'AddBy';
$lang['entities_hr_data_leave_request_AddDate'] = 'AddDate';
$lang['entities_hr_data_leave_request_EditBy'] = 'EditBy';
$lang['entities_hr_data_leave_request_EditDate'] = 'EditDate';
$lang['entities_hr_data_leave_request_TimeStamp'] = 'TimeStamp';
