<?php defined('BASEPATH') OR exit('No direct script access allowed');
$lang['entities_hr_users_Username'] = 'Username';
$lang['entities_hr_users_EmployeeId'] = 'EmployeeId';
$lang['entities_hr_users_Password'] = 'Password';
$lang['entities_hr_users_Email'] = 'Email';
$lang['entities_hr_users_Contact'] = 'Contact';
$lang['entities_hr_users_Name'] = 'Name';
$lang['entities_hr_users_Role'] = 'Role';
$lang['entities_hr_users_SecurityKey'] = 'SecurityKey';
$lang['entities_hr_users_ValidateToken'] = 'ValidateToken';
$lang['entities_hr_users_DeviceActive'] = 'DeviceActive';
$lang['entities_hr_users_Status'] = 'Status';
$lang['entities_hr_users_AddBy'] = 'AddBy';
$lang['entities_hr_users_AddDate'] = 'AddDate';
$lang['entities_hr_users_EditBy'] = 'EditBy';
$lang['entities_hr_users_EditDate'] = 'EditDate';
$lang['entities_hr_users_TimeStamp'] = 'TimeStamp';
