<?php defined('BASEPATH') OR exit('No direct script access allowed');
$lang['entities_tbl_pembina_NtaPembina'] = 'NtaPembina';
$lang['entities_tbl_pembina_NamaPembina'] = 'NamaPembina';
$lang['entities_tbl_pembina_AlamatPembina'] = 'AlamatPembina';
$lang['entities_tbl_pembina_TglLahirPembina'] = 'TglLahirPembina';
$lang['entities_tbl_pembina_HoHpPembina'] = 'HoHpPembina';
$lang['entities_tbl_pembina_AddBy'] = 'AddBy';
$lang['entities_tbl_pembina_AddDate'] = 'AddDate';
$lang['entities_tbl_pembina_EditBy'] = 'EditBy';
$lang['entities_tbl_pembina_EditDate'] = 'EditDate';
$lang['entities_tbl_pembina_TimeStamp'] = 'TimeStamp';
